version: "3.8"

services:
  mongoDB:
    image: mongo
    container_name: moongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - /Documents/database-data:/data/db